language: java
jdk:
  - oraclejdk7
  - oraclejdk6
  - oraclejdk5
  - openjdk7
  - openjdk6
  - openjdk5
install: mvn install -Dmaven.compiler.target=1.5 -Dmaven.compiler.source=1.5 -DskipTests=true -B
script: mvn test -Dmaven.compiler.target=1.5 -Dmaven.compiler.source=1.5 -B
