language: java
jdk:
  - oraclejdk8
  - oraclejdk7
#  - oraclejdk6
#  - oraclejdk5
  - openjdk7
  - openjdk6
#  - openjdk5
install: mvn install -DskipTests=true -B
script: mvn test -B

after_success:
  - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:cobertura
