pygments: true
relative_permalinks: false
url: http://owner.aeonbits.org
title: OWNER - Java(tm) properties reinvented.
description: Get rid of the boilerplate code in properties based configuration.
google_analytics_id: UA-462505-8
exclude: ["CNAME", "owner.aeonbits.org.iml", "README", "bin"]
permalink: /news/:year/:month/:day/:title

author :
  name : Luigi R. Viggiano
  email : luigi.viggiano@gmail.com
  github : lviggiano
  twitter : lviggiano

project:
  name: OWNER
  github: owner
  
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
