pygments: true
relative_permalinks: false
google_analytics_id: UA-462505-8
exclude: ["CNAME", "owner.aeonbits.org.iml", "README"]

author :
  name : Luigi R. Viggiano
  email : luigi.viggiano@gmail.com
  github : lviggiano
  twitter : lviggiano
  feedburner : feedname

project:
  name: OWNER
  github: owner